// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/learning/models/session/learning_session.dart';
import 'features/learning/models/session/learning_session_detail.dart';
import 'features/library/models/answer.dart';
import 'features/library/models/question.dart';
import 'features/library/models/quiz.dart';
import 'features/library/models/subject.dart';
import 'features/setting/models/app_config.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7299001762337608636),
    name: 'Answer',
    lastPropertyId: const obx_int.IdUid(6, 7090975204764991018),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2325787330488811032),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3725915927102138111),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7617466611591131423),
        name: 'isCorrect',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8858047260691144583),
        name: 'questionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 5668328145474128840),
        relationField: 'question',
        relationTarget: 'Question',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8111846479549212992),
        name: 'questionTargetId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7090975204764991018),
        name: 'indexOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'sessionDetails',
        srcEntity: 'LearningSessionDetail',
        srcField: 'selectedAnswers',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2787929510791643226),
    name: 'Question',
    lastPropertyId: const obx_int.IdUid(5, 6094649052072019045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8762669605337996739),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3373159414247983015),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7232779121486197463),
        name: 'explanation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7682172712956022625),
        name: 'quizId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 2294214439300309100),
        relationField: 'quiz',
        relationTarget: 'Quiz',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6094649052072019045),
        name: 'quizTargetId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'answers',
        srcEntity: 'Answer',
        srcField: 'question',
      ),
      obx_int.ModelBacklink(
        name: 'sessionDetails',
        srcEntity: 'LearningSessionDetail',
        srcField: 'question',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1223619618416249017),
    name: 'Quiz',
    lastPropertyId: const obx_int.IdUid(4, 8082341277111544156),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5665565707356688541),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6841576832027659918),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5528764215132486161),
        name: 'subjectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4860670046444866728),
        relationField: 'subject',
        relationTarget: 'Subject',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8082341277111544156),
        name: 'subjectTargetId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'questions',
        srcEntity: 'Question',
        srcField: 'quiz',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 5427150702711615976),
    name: 'Subject',
    lastPropertyId: const obx_int.IdUid(3, 6428952260522327864),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1917770060388419375),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1722259383235066722),
        name: 'code',
        type: 9,
        flags: 8,
        indexId: const obx_int.IdUid(5, 8093596476363037954),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6428952260522327864),
        name: 'name',
        type: 9,
        flags: 8,
        indexId: const obx_int.IdUid(6, 64838429502581854),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'quizzes',
        srcEntity: 'Quiz',
        srcField: 'subject',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 5502079073284747514),
    name: 'LearningSessionDetail',
    lastPropertyId: const obx_int.IdUid(8, 7482946366124564686),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4500498495062191630),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2853243639218834664),
        name: 'questionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(12, 8144178316381096788),
        relationField: 'question',
        relationTarget: 'Question',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7611788022201123908),
        name: 'isChecked',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2736716217999466047),
        name: 'isCorrect',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6075764298969602044),
        name: 'learningSessionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 4626027454110207633),
        relationField: 'learningSession',
        relationTarget: 'LearningSession',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1626576770022630230),
        name: 'questionTargetId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7482946366124564686),
        name: 'isSeen',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 9164081888470751568),
        name: 'selectedAnswers',
        targetId: const obx_int.IdUid(1, 7299001762337608636),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(14, 4024975291499176318),
    name: 'LearningSession',
    lastPropertyId: const obx_int.IdUid(26, 7350298590860599548),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2139771849035858923),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1915649893065070788),
        name: 'quizId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(15, 379639735380436061),
        relationField: 'quiz',
        relationTarget: 'Quiz',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6880168520543185269),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8018202501068506886),
        name: 'shuffleQuestions',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8782944028849370890),
        name: 'shuffleAnswers',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5806153554850083549),
        name: 'currentIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5954749709625237847),
        name: 'studyTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3448039748449309428),
        name: 'timeLimit',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1615231433326829010),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5355497963196388424),
        name: 'endTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5043944630363418254),
        name: 'totalCorrect',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4339430802236869996),
        name: 'totalWrong',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1423225547210962661),
        name: 'learningMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 7603499362119049651),
        name: 'quizTargetId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 7350298590860599548),
        name: 'recentLearningDateTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'learningSessionDetails',
        srcEntity: 'LearningSessionDetail',
        srcField: 'learningSession',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(16, 8389683534816014055),
    name: 'AppConfig',
    lastPropertyId: const obx_int.IdUid(6, 3902663401136427737),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4858525117380522530),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6109453532299970361),
        name: 'fontFamily',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8079069329336756909),
        name: 'fontSize',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6047167473738186567),
        name: 'enableQuickAnswer',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3813912160679431242),
        name: 'isMouseEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3902663401136427737),
        name: 'internalKeyBindings',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(16, 8389683534816014055),
    lastIndexId: const obx_int.IdUid(20, 4906833056168862516),
    lastRelationId: const obx_int.IdUid(7, 8362246070475913355),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      2396496313140079722,
      6739487655992466919,
      7194349862879057577,
      6906873933812241657,
      8360411958099064413,
      4920760139726279388,
      8150576158054074434,
      1763644831287437937,
      6666508573204862373,
    ],
    retiredIndexUids: const [
      7347700586798717336,
      1540933757665640831,
      1057985058308706369,
      2124571327299695343,
      1990295136756352924,
      4906833056168862516,
    ],
    retiredPropertyUids: const [
      2318664718927489466,
      1469496124070769133,
      431446778851679623,
      7643270234396130286,
      6052052327818296168,
      8865783141457715370,
      3891633060395384989,
      7736441094076709299,
      1696453458266817323,
      7648335953531946648,
      5090399111131249139,
      1389879549804047767,
      4727104150088434248,
      2588762595146629082,
      7396730447929605737,
      3238821516106579548,
      1107252762027705928,
      1029857459908663371,
      7751678349388760973,
      4470262085753244451,
      207792742453075706,
      9219255573129031638,
      3787887699994422139,
      2691725644729841894,
      1542399141675473973,
      4376342801507758870,
      3799893100331508462,
      5007406510879240317,
      8313303486853216815,
      2292195067885669370,
      2893115137991058569,
      1756388381936575352,
      3335254338794138722,
      5044642717077290212,
      6838168661107532394,
      807029031682210687,
      8381764252299684577,
      1534693929065098377,
      3498591134196635175,
      3042224249149290151,
      416160645542573053,
      3382275470442160643,
      3309331218319188588,
      743300853062294424,
      3346808843117044201,
      3866073489404391611,
      3008088718531470702,
      7011384055098797399,
      3489534141775928773,
      6866705681423524424,
      7406953079002698811,
      4203362015020571407,
      6432743908127437444,
      1984431815681446903,
      7821461955169100059,
      2375886395064797671,
      5449762714290267494,
      5020267360344102693,
      6782761673313341965,
      7901090139982536841,
      5574867939183545413,
      2048883277171867967,
      7694388355315084928,
      8311825790142595191,
      2509792507103309050,
      4159561241139744136,
      7059512946458057891,
      4624251156133090159,
      1633947576123433121,
      1791929882753651045,
      784355124677444192,
      2677701699688802950,
      3979924762343533953,
      1626040663082795045,
      6457038153511764670,
      5591443815765498871,
      4946847597482540535,
      6197788571439081836,
      8589941123766075979,
      4138805812257400070,
      105753599878439496,
      3979669503206411504,
      2022142046752544118,
      278735688862174139,
      4586895986591858850,
      3132814561602497699,
      5970557713969293238,
      171667533933627104,
      679835317048731491,
      7003676796610611212,
      1563705108099211498,
      1966622745110527815,
      1535566084756155748,
      8505331117145444507,
      6678169052645426052,
      9047396285256898018,
      6141873939163442509,
      8584605567879980311,
      7037096859418411473,
      5894548907070236658,
      8072267530557979247,
      3411991043566285988,
      2385495259337550541,
      7461321401101591390,
      2631531781013020662,
      5105569352636023297,
      3683074668220061082,
      7121853349119296041,
      1248859767542364344,
      6106360613448998475,
      920426485979270051,
      1658124175764256579,
      5935642483109839422,
      2152236491451129832,
      563601163632320191,
      7060876806625588756,
      2626478897613327985,
      2866774429764172645,
      6849748057573735533,
      4223561616545082578,
      1121915151140772739,
      5219982983962142832,
      6502654617316206455,
      3904131708249950806,
      411770755522709919,
    ],
    retiredRelationUids: const [
      604733439351293478,
      8764137301684483581,
      209961309989937723,
      7656245509509046707,
      8362246070475913355,
    ],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Answer: obx_int.EntityDefinition<Answer>(
      model: _entities[0],
      toOneRelations: (Answer object) => [object.question],
      toManyRelations: (Answer object) => {
        obx_int.RelInfo<LearningSessionDetail>.toManyBacklink(2, object.id):
            object.sessionDetails,
      },
      getId: (Answer object) => object.id,
      setId: (Answer object, int id) {
        object.id = id;
      },
      objectToFB: (Answer object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addBool(2, object.isCorrect);
        fbb.addInt64(3, object.question.targetId);
        fbb.addInt64(4, object.questionTargetId);
        fbb.addInt64(5, object.indexOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isCorrectParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final indexOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final questionTargetIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Answer(
          id: idParam,
          content: contentParam,
          isCorrect: isCorrectParam,
          indexOrder: indexOrderParam,
          questionTargetId: questionTargetIdParam,
        );
        object.question.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.question.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Answer>(
          object.sessionDetails,
          store,
          obx_int.RelInfo<LearningSessionDetail>.toManyBacklink(2, object.id),
        );
        return object;
      },
    ),
    Question: obx_int.EntityDefinition<Question>(
      model: _entities[1],
      toOneRelations: (Question object) => [object.quiz],
      toManyRelations: (Question object) => {
        obx_int.RelInfo<Answer>.toOneBacklink(
          4,
          object.id,
          (Answer srcObject) => srcObject.question,
        ): object.answers,
        obx_int.RelInfo<LearningSessionDetail>.toOneBacklink(
          3,
          object.id,
          (LearningSessionDetail srcObject) => srcObject.question,
        ): object.sessionDetails,
      },
      getId: (Question object) => object.id,
      setId: (Question object, int id) {
        object.id = id;
      },
      objectToFB: (Question object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final explanationOffset = fbb.writeString(object.explanation);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addOffset(2, explanationOffset);
        fbb.addInt64(3, object.quiz.targetId);
        fbb.addInt64(4, object.quizTargetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final explanationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final quizTargetIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Question(
          id: idParam,
          content: contentParam,
          explanation: explanationParam,
          quizTargetId: quizTargetIdParam,
        );
        object.quiz.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.quiz.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Question>(
          object.answers,
          store,
          obx_int.RelInfo<Answer>.toOneBacklink(
            4,
            object.id,
            (Answer srcObject) => srcObject.question,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Question>(
          object.sessionDetails,
          store,
          obx_int.RelInfo<LearningSessionDetail>.toOneBacklink(
            3,
            object.id,
            (LearningSessionDetail srcObject) => srcObject.question,
          ),
        );
        return object;
      },
    ),
    Quiz: obx_int.EntityDefinition<Quiz>(
      model: _entities[2],
      toOneRelations: (Quiz object) => [object.subject],
      toManyRelations: (Quiz object) => {
        obx_int.RelInfo<Question>.toOneBacklink(
          4,
          object.id,
          (Question srcObject) => srcObject.quiz,
        ): object.questions,
      },
      getId: (Quiz object) => object.id,
      setId: (Quiz object, int id) {
        object.id = id;
      },
      objectToFB: (Quiz object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.subject.targetId);
        fbb.addInt64(3, object.subjectTargetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final subjectTargetIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Quiz(
          id: idParam,
          name: nameParam,
          subjectTargetId: subjectTargetIdParam,
        );
        object.subject.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.subject.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Quiz>(
          object.questions,
          store,
          obx_int.RelInfo<Question>.toOneBacklink(
            4,
            object.id,
            (Question srcObject) => srcObject.quiz,
          ),
        );
        return object;
      },
    ),
    Subject: obx_int.EntityDefinition<Subject>(
      model: _entities[3],
      toOneRelations: (Subject object) => [],
      toManyRelations: (Subject object) => {
        obx_int.RelInfo<Quiz>.toOneBacklink(
          3,
          object.id,
          (Quiz srcObject) => srcObject.subject,
        ): object.quizzes,
      },
      getId: (Subject object) => object.id,
      setId: (Subject object, int id) {
        object.id = id;
      },
      objectToFB: (Subject object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Subject(id: idParam, code: codeParam, name: nameParam);
        obx_int.InternalToManyAccess.setRelInfo<Subject>(
          object.quizzes,
          store,
          obx_int.RelInfo<Quiz>.toOneBacklink(
            3,
            object.id,
            (Quiz srcObject) => srcObject.subject,
          ),
        );
        return object;
      },
    ),
    LearningSessionDetail: obx_int.EntityDefinition<LearningSessionDetail>(
      model: _entities[4],
      toOneRelations: (LearningSessionDetail object) => [
        object.question,
        object.learningSession,
      ],
      toManyRelations: (LearningSessionDetail object) => {
        obx_int.RelInfo<LearningSessionDetail>.toMany(2, object.id):
            object.selectedAnswers,
      },
      getId: (LearningSessionDetail object) => object.id,
      setId: (LearningSessionDetail object, int id) {
        object.id = id;
      },
      objectToFB: (LearningSessionDetail object, fb.Builder fbb) {
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(2, object.question.targetId);
        fbb.addBool(3, object.isChecked);
        fbb.addBool(4, object.isCorrect);
        fbb.addInt64(5, object.learningSession.targetId);
        fbb.addInt64(6, object.questionTargetId);
        fbb.addBool(7, object.isSeen);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final isCheckedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final isSeenParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isCorrectParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final questionTargetIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = LearningSessionDetail(
          id: idParam,
          isChecked: isCheckedParam,
          isSeen: isSeenParam,
          isCorrect: isCorrectParam,
          questionTargetId: questionTargetIdParam,
        );
        object.question.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.question.attach(store);
        object.learningSession.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.learningSession.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<LearningSessionDetail>(
          object.selectedAnswers,
          store,
          obx_int.RelInfo<LearningSessionDetail>.toMany(2, object.id),
        );
        return object;
      },
    ),
    LearningSession: obx_int.EntityDefinition<LearningSession>(
      model: _entities[5],
      toOneRelations: (LearningSession object) => [object.quiz],
      toManyRelations: (LearningSession object) => {
        obx_int.RelInfo<LearningSessionDetail>.toOneBacklink(
          6,
          object.id,
          (LearningSessionDetail srcObject) => srcObject.learningSession,
        ): object.learningSessionDetails,
      },
      getId: (LearningSession object) => object.id,
      setId: (LearningSession object, int id) {
        object.id = id;
      },
      objectToFB: (LearningSession object, fb.Builder fbb) {
        final learningModeOffset = fbb.writeString(object.learningMode);
        fbb.startTable(27);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quiz.targetId);
        fbb.addInt64(3, object.startTime.millisecondsSinceEpoch);
        fbb.addBool(4, object.shuffleQuestions);
        fbb.addBool(5, object.shuffleAnswers);
        fbb.addInt64(6, object.currentIndex);
        fbb.addInt64(7, object.studyTime);
        fbb.addInt64(8, object.timeLimit);
        fbb.addBool(9, object.isCompleted);
        fbb.addInt64(10, object.endTime?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.totalCorrect);
        fbb.addInt64(12, object.totalWrong);
        fbb.addOffset(20, learningModeOffset);
        fbb.addInt64(23, object.quizTargetId);
        fbb.addInt64(25, object.recentLearningDateTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final recentLearningDateTimeValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 54);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final learningModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final recentLearningDateTimeParam = recentLearningDateTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(recentLearningDateTimeValue);
        final shuffleQuestionsParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final shuffleAnswersParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final currentIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final studyTimeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final timeLimitParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final endTimeParam = endTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endTimeValue);
        final totalCorrectParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final totalWrongParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final quizTargetIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          50,
          0,
        );
        final object = LearningSession(
          id: idParam,
          learningMode: learningModeParam,
          startTime: startTimeParam,
          recentLearningDateTime: recentLearningDateTimeParam,
          shuffleQuestions: shuffleQuestionsParam,
          shuffleAnswers: shuffleAnswersParam,
          currentIndex: currentIndexParam,
          studyTime: studyTimeParam,
          timeLimit: timeLimitParam,
          isCompleted: isCompletedParam,
          endTime: endTimeParam,
          totalCorrect: totalCorrectParam,
          totalWrong: totalWrongParam,
          quizTargetId: quizTargetIdParam,
        );
        object.quiz.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.quiz.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<LearningSession>(
          object.learningSessionDetails,
          store,
          obx_int.RelInfo<LearningSessionDetail>.toOneBacklink(
            6,
            object.id,
            (LearningSessionDetail srcObject) => srcObject.learningSession,
          ),
        );
        return object;
      },
    ),
    AppConfig: obx_int.EntityDefinition<AppConfig>(
      model: _entities[6],
      toOneRelations: (AppConfig object) => [],
      toManyRelations: (AppConfig object) => {},
      getId: (AppConfig object) => object.id,
      setId: (AppConfig object, int id) {
        object.id = id;
      },
      objectToFB: (AppConfig object, fb.Builder fbb) {
        final fontFamilyOffset = fbb.writeString(object.fontFamily);
        final internalKeyBindingsOffset = fbb.writeString(
          object.internalKeyBindings,
        );
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fontFamilyOffset);
        fbb.addFloat64(2, object.fontSize);
        fbb.addBool(3, object.enableQuickAnswer);
        fbb.addBool(4, object.isMouseEnabled);
        fbb.addOffset(5, internalKeyBindingsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fontFamilyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fontSizeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final enableQuickAnswerParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final isMouseEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final internalKeyBindingsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = AppConfig(
          id: idParam,
          fontFamily: fontFamilyParam,
          fontSize: fontSizeParam,
          enableQuickAnswer: enableQuickAnswerParam,
          isMouseEnabled: isMouseEnabledParam,
          internalKeyBindings: internalKeyBindingsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Answer] entity fields to define ObjectBox queries.
class Answer_ {
  /// See [Answer.id].
  static final id = obx.QueryIntegerProperty<Answer>(
    _entities[0].properties[0],
  );

  /// See [Answer.content].
  static final content = obx.QueryStringProperty<Answer>(
    _entities[0].properties[1],
  );

  /// See [Answer.isCorrect].
  static final isCorrect = obx.QueryBooleanProperty<Answer>(
    _entities[0].properties[2],
  );

  /// See [Answer.question].
  static final question = obx.QueryRelationToOne<Answer, Question>(
    _entities[0].properties[3],
  );

  /// See [Answer.questionTargetId].
  static final questionTargetId = obx.QueryIntegerProperty<Answer>(
    _entities[0].properties[4],
  );

  /// See [Answer.indexOrder].
  static final indexOrder = obx.QueryIntegerProperty<Answer>(
    _entities[0].properties[5],
  );
}

/// [Question] entity fields to define ObjectBox queries.
class Question_ {
  /// See [Question.id].
  static final id = obx.QueryIntegerProperty<Question>(
    _entities[1].properties[0],
  );

  /// See [Question.content].
  static final content = obx.QueryStringProperty<Question>(
    _entities[1].properties[1],
  );

  /// See [Question.explanation].
  static final explanation = obx.QueryStringProperty<Question>(
    _entities[1].properties[2],
  );

  /// See [Question.quiz].
  static final quiz = obx.QueryRelationToOne<Question, Quiz>(
    _entities[1].properties[3],
  );

  /// See [Question.quizTargetId].
  static final quizTargetId = obx.QueryIntegerProperty<Question>(
    _entities[1].properties[4],
  );

  /// see [Question.answers]
  static final answers = obx.QueryBacklinkToMany<Answer, Question>(
    Answer_.question,
  );

  /// see [Question.sessionDetails]
  static final sessionDetails =
      obx.QueryBacklinkToMany<LearningSessionDetail, Question>(
        LearningSessionDetail_.question,
      );
}

/// [Quiz] entity fields to define ObjectBox queries.
class Quiz_ {
  /// See [Quiz.id].
  static final id = obx.QueryIntegerProperty<Quiz>(_entities[2].properties[0]);

  /// See [Quiz.name].
  static final name = obx.QueryStringProperty<Quiz>(_entities[2].properties[1]);

  /// See [Quiz.subject].
  static final subject = obx.QueryRelationToOne<Quiz, Subject>(
    _entities[2].properties[2],
  );

  /// See [Quiz.subjectTargetId].
  static final subjectTargetId = obx.QueryIntegerProperty<Quiz>(
    _entities[2].properties[3],
  );

  /// see [Quiz.questions]
  static final questions = obx.QueryBacklinkToMany<Question, Quiz>(
    Question_.quiz,
  );
}

/// [Subject] entity fields to define ObjectBox queries.
class Subject_ {
  /// See [Subject.id].
  static final id = obx.QueryIntegerProperty<Subject>(
    _entities[3].properties[0],
  );

  /// See [Subject.code].
  static final code = obx.QueryStringProperty<Subject>(
    _entities[3].properties[1],
  );

  /// See [Subject.name].
  static final name = obx.QueryStringProperty<Subject>(
    _entities[3].properties[2],
  );

  /// see [Subject.quizzes]
  static final quizzes = obx.QueryBacklinkToMany<Quiz, Subject>(Quiz_.subject);
}

/// [LearningSessionDetail] entity fields to define ObjectBox queries.
class LearningSessionDetail_ {
  /// See [LearningSessionDetail.id].
  static final id = obx.QueryIntegerProperty<LearningSessionDetail>(
    _entities[4].properties[0],
  );

  /// See [LearningSessionDetail.question].
  static final question =
      obx.QueryRelationToOne<LearningSessionDetail, Question>(
        _entities[4].properties[1],
      );

  /// See [LearningSessionDetail.isChecked].
  static final isChecked = obx.QueryBooleanProperty<LearningSessionDetail>(
    _entities[4].properties[2],
  );

  /// See [LearningSessionDetail.isCorrect].
  static final isCorrect = obx.QueryBooleanProperty<LearningSessionDetail>(
    _entities[4].properties[3],
  );

  /// See [LearningSessionDetail.learningSession].
  static final learningSession =
      obx.QueryRelationToOne<LearningSessionDetail, LearningSession>(
        _entities[4].properties[4],
      );

  /// See [LearningSessionDetail.questionTargetId].
  static final questionTargetId =
      obx.QueryIntegerProperty<LearningSessionDetail>(
        _entities[4].properties[5],
      );

  /// See [LearningSessionDetail.isSeen].
  static final isSeen = obx.QueryBooleanProperty<LearningSessionDetail>(
    _entities[4].properties[6],
  );

  /// see [LearningSessionDetail.selectedAnswers]
  static final selectedAnswers =
      obx.QueryRelationToMany<LearningSessionDetail, Answer>(
        _entities[4].relations[0],
      );
}

/// [LearningSession] entity fields to define ObjectBox queries.
class LearningSession_ {
  /// See [LearningSession.id].
  static final id = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[0],
  );

  /// See [LearningSession.quiz].
  static final quiz = obx.QueryRelationToOne<LearningSession, Quiz>(
    _entities[5].properties[1],
  );

  /// See [LearningSession.startTime].
  static final startTime = obx.QueryDateProperty<LearningSession>(
    _entities[5].properties[2],
  );

  /// See [LearningSession.shuffleQuestions].
  static final shuffleQuestions = obx.QueryBooleanProperty<LearningSession>(
    _entities[5].properties[3],
  );

  /// See [LearningSession.shuffleAnswers].
  static final shuffleAnswers = obx.QueryBooleanProperty<LearningSession>(
    _entities[5].properties[4],
  );

  /// See [LearningSession.currentIndex].
  static final currentIndex = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[5],
  );

  /// See [LearningSession.studyTime].
  static final studyTime = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[6],
  );

  /// See [LearningSession.timeLimit].
  static final timeLimit = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[7],
  );

  /// See [LearningSession.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<LearningSession>(
    _entities[5].properties[8],
  );

  /// See [LearningSession.endTime].
  static final endTime = obx.QueryDateProperty<LearningSession>(
    _entities[5].properties[9],
  );

  /// See [LearningSession.totalCorrect].
  static final totalCorrect = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[10],
  );

  /// See [LearningSession.totalWrong].
  static final totalWrong = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[11],
  );

  /// See [LearningSession.learningMode].
  static final learningMode = obx.QueryStringProperty<LearningSession>(
    _entities[5].properties[12],
  );

  /// See [LearningSession.quizTargetId].
  static final quizTargetId = obx.QueryIntegerProperty<LearningSession>(
    _entities[5].properties[13],
  );

  /// See [LearningSession.recentLearningDateTime].
  static final recentLearningDateTime = obx.QueryDateProperty<LearningSession>(
    _entities[5].properties[14],
  );

  /// see [LearningSession.learningSessionDetails]
  static final learningSessionDetails =
      obx.QueryBacklinkToMany<LearningSessionDetail, LearningSession>(
        LearningSessionDetail_.learningSession,
      );
}

/// [AppConfig] entity fields to define ObjectBox queries.
class AppConfig_ {
  /// See [AppConfig.id].
  static final id = obx.QueryIntegerProperty<AppConfig>(
    _entities[6].properties[0],
  );

  /// See [AppConfig.fontFamily].
  static final fontFamily = obx.QueryStringProperty<AppConfig>(
    _entities[6].properties[1],
  );

  /// See [AppConfig.fontSize].
  static final fontSize = obx.QueryDoubleProperty<AppConfig>(
    _entities[6].properties[2],
  );

  /// See [AppConfig.enableQuickAnswer].
  static final enableQuickAnswer = obx.QueryBooleanProperty<AppConfig>(
    _entities[6].properties[3],
  );

  /// See [AppConfig.isMouseEnabled].
  static final isMouseEnabled = obx.QueryBooleanProperty<AppConfig>(
    _entities[6].properties[4],
  );

  /// See [AppConfig.internalKeyBindings].
  static final internalKeyBindings = obx.QueryStringProperty<AppConfig>(
    _entities[6].properties[5],
  );
}
